export const GET_WEATHER_BEGIN = 'GET_WEATHER_BEGIN'
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS'
export const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR'
export const ADD_FAVORITE_BEGIN = 'ADD_FAVORITES_BEGIN'
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS'
export const ADD_FAVORITE_ERROR = 'ADD_FAVORITE_ERROR'
export const GET_FAVORITES_SUCCESS = 'ADD_FAVORITES'
export const GET_FAVORITES_ERROR = 'GET_FAVORITES_ERROR'
export const DELETE_FAVORITE = 'DELETE_FAVORITE'






